
use sakila;
show tables;
select*from rental;
select*from category;
select*from sales_by_store;
select*from inventory;
#Retrieve the names of all the films in the Sakila database
select * from film;
#Display the titles of films released in the year 2006.
select title,release_year from film where release_year='2006';
#List the distinct categories of films available in the database.
select distinct c.name from category c
join film_category fc on c.category_id=fc.category_id
join film f on fc.film_id=f.film_id;
#Find the total number of customers in the database.
select count(customer_id) from customer;
#Retrieve the first name and last name of all the customers.
select first_name,last_name from customer;
#List the rental dates for a specific film (choose any film you like).
select r.rental_date from rental r join inventory i on r.inventory_id=i.inventory_id join film f on i.film_id=f.film_id where f.title
='ACADEMY DINOSAUR';
#Calculate the total revenue generated by the rental store.
select sum(amount) as totalrevenue from payment;
select sum(total_sales)from sales_by_store;
#Display the top 5 customers who have rented the most films.
select c.customer_id,concat(c.first_name,' ',c.last_name) as customer_name,count(r.rental_id)
as rental_count from customer c
join rental r on c.customer_id=r.customer_id 
group by c.customer_id order by rental_count desc limit 5;
#Find the films that are not in stock currently.
select title from film  except select f.title from film f join inventory i on f.film_id=i.film_id;
#List the films that are available in the Comedy category.
select f.title,c.name as cname from film f join 
(select fc.film_id from film_category fc join (select c.category_id from category c where name='Comedy') co on fc.category_id=co.category_id) k 
on f.film_id=k.film_id
JOIN category c ON c.name = 'Comedy';
#Retrieve the film title and the number of times it has been rented.
select f.title as filmtitle ,count(r.rental_id) as rental_count
from film f join inventory i on f.film_id=i.film_id 
join rental r on i.inventory_id=r.inventory_id 
group by filmtitle
order by rental_count desc;
#Find the most rented film in the database.
select f.title as filmtitle ,count(r.rental_id) as rental_count
from film f join inventory i on f.film_id=i.film_id 
join rental r on i.inventory_id=r.inventory_id 
group by filmtitle
order by rental_count desc
limit 1;
#Calculate the average rental duration of films.
select avg(datediff(r.return_date,r.rental_date)) as average_rental_duration from rental r;
#List the customers who have not rented any films.
select concat(c.first_name,' ',c.last_name) as customer_name from customer c 
left join rental r on c.customer_id=r.customer_id
group by customer_name;
#calculate the total revenue generated by each customer.
select p.customer_id ,sum(amount)as revenue_per_customer,concat(c.first_name,' ',c.last_name) as customer_name
from payment p
join customer c on 
p.customer_id=c.customer_id
group by customer_id;